---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-pvc
  labels:
    project: workshop4
  namespace: workshop4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db-deploy
  labels:
    project: workshop4
  namespace: workshop4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-db
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      volumes:
        - name: wordpress-db-volume
          persistentVolumeClaim:
            claimName: wordpress-db-pvc
      containers:
      - name: wordpress-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
          - name: wordpress-db-volume
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-db-secret
                key: root_password
        

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-db-service
  namespace: workshop4
  labels:
    project: workshop4
spec:
  selector:
    app: wordpress-db
  ports:
  - port: 3306
    targetPort: 3306
